import math
import os
os.system("say -v Milena Привет! I do addition for you, yes?")
input("Привет! I do addition for you, yes? ")
os.system("say -v Milena Too late, I do anyway!")
print("Too late, I do anyway!")
os.system("say -v Milena Give me number")
add_1 = input("Give me number: ")
os.system("say -v Milena One more, пожалуйста")
add_2 = input("One more, пожалуйста: ")
add_1 = float(add_1)
add_2 = float(add_2)
sum = add_1 + add_2
print("Addition of",add_1," and",add_2," is "+str(sum)+".")
os.system("say -v Milena Addition of your numbers equal"+str(sum))
os.system("say -v Milena Now I do multiplication of 3 numbers! Give me first one")
times_1 = input("Now I do multiplication of 3 numbers! Give me first one: ")
os.system("say -v Milena Another")
times_2 = input("Another: ")
os.system("say -v Milena Last one, пожалуйста")
times_3 = input("Last one, пожалуйста: ")
times_1 = float(times_1)
times_2 = float(times_2)
times_3 = float(times_3)
product = times_1 * times_2 * times_3
print("Your answer of multiplication is "+str(product)+".")
os.system("say -v Milena Your answer of multiplication is "+str(product))
os.system("say -v Milena PROGRAM IS END")
print("PROGRAM IS END")