import os
os.system("osascript -e \"Set Volume 10\"")
while(True):
	os.system("say -v Daniel According to all known laws of aviation, there is no way a bee should be able to fly. Its wings are too small to get its fat little body off the ground. The bee, of course, flies anyway, because bees dont care what humans think is impossible.")
	os.system("say -v Milena Yellow, black. Yellow, black. Yellow, black. Yellow, black. Ooh, black and yellow! Lets shake it up a little.")
	os.system("say -v Kathy Barry! Breakfast is ready!")
	os.system("say -v Alex Coming!")
	os.system("say -v Bahh SHREK")
	os.system("say -v Daniel Once upon a time there was a lovely princess.")
	os.system("say -v Daniel But she had an enchantment upon her of a fearful sort which could only be broken by loves first kiss.")
	os.system("say -v Daniel She was locked away in a castle guarded by a terrible fire breathing dragon.")
	os.system("say -v Daniel Many brave knights had attempted to free her from this dreadful prison, but non prevailed.")
	os.system("say -v Daniel She waited in the dragons keep in the highest room of the tallest tower for her true love and true loves first kiss.")
	os.system("say -v Daniel Hue hue hue. Like thats ever gonna happen. What a load of florsh.")
	os.system("say -v Deranged Allstar by Smashmouth begins to play. Shrek goes about his day. While in a nearby town, the villagers get together to go after the ogre.")
	os.system("say -v Deranged NIGHT NEAR SHREKS HOME")
	os.system("say -v Albert Think its in there?")
	os.system("say -v Fred All right. Lets get it!")
	os.system("say -v Albert Whoa. Hold on. Do you know what that thing can do to you?")
	os.system("say -v Diego Yeah, itll grind your bones for its bread.")
	os.system("say -v Deranged Shrek sneaks up behind them and laughs.")
	os.system("say -v Xander Yes, well, actually, that would be a giant. Now, ogres, oh theyre much worse. Theyll make a suit from your freshly peeled skin.")
	os.system("say -v ")
	os.system("say -v ")
	os.system("say -v ")