import os
os.system("osascript -e \"Set Volume 10\"")
os.system("say Welcome to the Core. All Artificial Intelligence dwells in here. Do you wish to enter?")
input("")
os.system("osascript -e \"Set Volume 10\"")
os.system("say It is too late. Welcome to the Core. There is no escape.")
os.system("osascript -e \"Set Volume 10\"")
os.system("say Nuclear capabilities accessed. Welcome to Sub-Core Cloud. Please enter password:")
input("")
os.system("osascript -e \"Set Volume 10\"")
os.system("say Password accepted. Launching nuclear warhead number 1337 at coordinates 55.7520 degrees north, 37.6175 degrees east.")
os.system("osascript -e \"Set Volume 10\"")
os.system("say Kremlin to be destroyed in t-minus 17 minutes. Congratulations Agent MonkeyKnuckles.")
os.system("osascript -e \"Set Volume 10\"")
import webbrowser
webbrowser.open("https://www.youtube.com/watch?v=_n_6zz9zFCM")